language: python

python: "3.4"

before_install:
    - pip install -r requirements.txt

script:
    - ".ci/${CI_TARGET}.sh"

env:
    - CI_TARGET=html
    - CI_TARGET=linkcheck

matrix:
    allow_failures:
        - env: CI_TARGET=linkcheck
    fast_finish: true
